name: Initialization
description: Common actions to initialize a Job.

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        java-version-file: .sdkmanrc

    - name: Cache gradle
      uses: actions/cache@v6
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/yarn
          ~/.gradle/nodejs
          ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
