name: Build

on:
  push:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: Build on ${{ matrix.os.runner }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.os.shell }}
    strategy:
      matrix:
        os:
          - runner: macos-latest
            shell: bash
          - runner: windows-latest
            shell: msys2 {0}
          - runner: ubuntu-latest
            shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt

      - name: Cache gradle
        if: ${{ inputs.jdk != '' }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set permission to execute gradle
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
