name: Build

on:
  push:
    branches-ignore:
      - "v*" # Skip tags
  workflow_dispatch:
    inputs:
      upload-report:
        description: 'Upload the test report'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2

  format:
    needs: [ validation ]
    name: Verify Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialization
        uses: ./.github/actions/init

      - name: Check format
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ktlintCheck

  build:
    needs: [ validation, format ]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
    #          - os: windows-latest -> No matching manifest when pulling Vault image
    #          - os: macos-latest -> Docker-compose command not found
    steps:
      - uses: actions/checkout@v4

      - name: Initialization
        id: init
        uses: ./.github/actions/init
        with:
          jdk: 8

      - name: Setup Kubernetes
        id: kubernetes
        uses: ./.github/actions/kubernetes

      - name: Docker Compose up
        run: docker-compose up -d

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
        env:
          KUBERNETES_IP: ${{ steps.kubernetes.outputs.ip }}
          KUBERNETES_PORT: ${{ steps.kubernetes.outputs.port }}
          KUBERNETES_TOKEN: ${{ steps.kubernetes.outputs.token }}

      - name: Upload test report
        if: ${{ github.event.inputs.upload-report == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests
          retention-days: 1
